meals/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "meals#index"
  resources :meals
  resources :foods
end

meals/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

meals/app/models/food.rb
class Food < ApplicationRecord

end

meals/app/models/meal.rb
class Meal < ApplicationRecord

end

meals/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

meals/app/controllers/foods_controller.rb
class FoodsController < ApplicationController

  def index
    @foods = Food.all
  end

  def show
    @food = Food.find(params[:id])
  end

  def new
    @food = Food.new
  end

  def edit
    @food = Food.find(params[:id])
  end

  def create
    @food = Food.new(food_params)

    @food.save

    redirect_to foods_path(@food)
  end

  def update
  @food = Food.find(params[:id])
  @food.update(food_params)

  redirect_to @food
end

def destroy
  @food = Food.find(params[:id])
  @food.destroy

  redirect_to foods_path
end


private

  def food_params
    params.require(:food).permit(:food_type, :calories, :img_url, :describe)
  end

end

meals/app/controllers/meals_controller.rb
class MealsController < ApplicationController

  def index
    @meals = Meal.all
  end

  def show
    @meal = Meal.find(params[:id])
    # @food = Food.find(params[:id])
  end

  def new
    @meal = Meal.new
  end

  def edit
    @meal = Meal.find(params[:id])
  end

  def create
    @meal = Meal.new(meal_params)

    @meal.save

    redirect_to meals_path(@meal)
  end

  def update
    @meal = Meal.find(params[:id])
    @meal.update(meal_params)

  redirect_to @meal
  end

  def destroy
    @meal = Meal.find(params[:id])
    @meal.destroy

    redirect_to meals_path
  end

private

  def meal_params
    params.require(:meal).permit(:title, :img_url, :main, :side)
  end

end

meals/app/helpers/application_helper.rb
module ApplicationHelper
end

meals/app/views/foods/edit.html.erb
<div class="edit_food">
<h1><%= @food.food_type %> </h1>

<%= form_for @food do |f| %>

  <h2><%= f.label :food_type %></h2>
  <%= f.text_field :food_type %>

  <h2><%= f.label :calories %></h2>
  <%= f.text_field :calories%>

  <h2><%= f.label :img_url %></h2>
  <%= f.text_field :img_url %>

  <h2><%= f.label :describe %><h2>
  <%= f.text_field :describe %>

<br>
<br>
  <%= f.submit %>
<% end %>

<%= form_for @food, method: :delete do |f| %>
  <%= f.submit "Delete!", class: "delete" %>
<% end %>
</div>

meals/app/views/foods/index.html.erb
<h1>All Foods Here</h1>

<% @foods.each do |food| %>
<div class="foods">
  <h3>Type of Food: <%= food.food_type %></h3>
  <h3>Calories: <%= food.calories %></h3>
  <h4><%= link_to "Show Food", food %></h4>

    <h3><%= image_tag food.img_url %> </h3>
</div>

<% end %>

meals/app/views/foods/new.html.erb
<h1>Add New Food</h1>

<%= form_for @food do |f| %>
  <h2><%= f.label :food %></h2>
      <%= f.text_field :food_type %>

  <h2><%= f.label :calories %></h2>
      <%= f.text_field :calories %>

  <h2><%= f.label :image %></h2>
      <%= f.text_field :img_url%>

  <h2><%= f.label :describe %></h2>
      <%= f.text_field :describe %>

  <h3><%= f.submit %></h3>

  <% end %>

  <br>

http://bit.ly/2luE7II

meals/app/views/foods/show.html.erb
<h1><%= @food.food_type %> </h1>

<div class="user_food">

<%= link_to "EDIT", edit_food_path %>
  <h4>Calories: <%= @food.calories %></h4>
  <h3><%= image_tag @food.img_url %> </h3>
  <h3>Description: <%= @food.describe %></h3>
</div>

meals/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Meals</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <h3><%= link_to "All Meals", meals_path %> | <%= link_to "Add New Meal", new_meal_path %></h3>
    <h3><%= link_to "All Foods", foods_path %> | <%= link_to "Add New Food", new_food_path %></h3>
    <%= yield %>
  </body>
</html>

meals/app/views/meals/edit.html.erb
<div class="edit_meal">
<h1>Edit <%=@meal.title %> </h1>

<%= form_for @meal do |f| %>
  <h2><%= f.label :title %></h2>
  <%= f.text_field :title %>

  <h2><%= f.label :image %></h2>
  <%= f.text_field :img_url%>

  <h2><%= f.label :main %></h2>
  <%= f.text_field :main %>

  <h2><%= f.label :side %></h2>
  <%= f.text_field :side %>
  <br>
  <br>
  <%= f.submit %>
<% end %>

<%= form_for @meal, method: :delete do |f| %>
  <%= f.submit "Delete!", class: "delete" %>
<% end %>
</div>

meals/app/views/meals/index.html.erb
<h1>User Created Meals</h1>

<% @meals.each do |meal| %>
<div class="meals">
  <p><%= link_to meal.title, meal %></p>
  <p><%#= link_to meal.img_url, meal %></p>
  <img src="<%= meal.img_url %>">
</div>

<% end %>

meals/app/views/meals/new.html.erb
<h1>Add New Meal</h1>

<%= form_for @meal do |m| %>
  <h2><%= m.label :title %></h2>
      <%= m.text_field :title %>

  <h2><%= m.label :img_url %></h2>
      <%= m.text_field :img_url %>

  <h2><%= m.label :main %></h2>
      <%= m.text_field :main %>

  <h2><%= m.label :side %></h2>
      <%= m.text_field :side %>

  <h3><%= m.submit %></h3>

  <% end %>

meals/app/views/meals/show.html.erb
<h1>Show Meal</h1>


<div class="user_meal">

<%= link_to "EDIT", edit_meal_path %>
  <h2>Main: </h2>
  <h3><%= @meal.main %></h3>
  <h3><%#= image_tag @food.img_url %> </h3>

  <h2>Side: </h3>
  <h3><%= @meal.side %></h3>
  <h3><%#= image_tag @food.img_url %> </h3>


</div>